//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MidAssignment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RsFood
    {
        public int id { get; set; }
        public int Restaurantid { get; set; }
        public int Foodid { get; set; }
    
        public virtual Food Food { get; set; }
        public virtual Restaurant Restaurant { get; set; }
    }
}
